### ISSUE TITLE
Error at 'make'

### ISSUE THREAD

**Issue by Gabriano** [part-cw/lambdanative#70] opened 2015-09-12 19:19 UTC
Following the instructions for a new install, I get the following error
== Error ==
... all is fine until :
=> extracting /Users/eric/Library/Caches/lambdanative/packages/gambc-v4_7_3.tgz..
 => configuring source..
 => patching source...
 => compiling source..
 => compiling source..
 => cleaning up..
 => liblambdanative..
 => cleaning up..
 => exploding library libgambc..
 => exploding library liblambdanative..
 => exploding library libz..
 => exploding library libpng..
 => exploding library libfreetype..
 => exploding library libjpeg..
 => exploding library libgd..
 => compiling scheme payload..
    /Users/eric/Documents/dev/scheme/lambdanative/modules/config/config.scm ..
    /Users/eric/Documents/dev/scheme/lambdanative/modules/ln_core/ln_core.scm ..
 gcc  -DMACOSX -m64  -D___SINGLE_HOST -D___LIBRARY -D___PRIMAL -DSTANDALONE -c -o /Users/eric/Library/Caches/lambdanative/macosx/build/597850315.o /Users/eric/Library/Caches/lambdanative/macosx/build/597850315.c -I/Users/eric/Library/Caches/lambdanative/macosx/include -I/Users/eric/Library/Caches/lambdanative/macosx/include/freetype2 -I/Users/eric/Documents/dev/scheme/lambdanative/modules/ln_core
/Users/eric/Library/Caches/lambdanative/macosx/build/597850315.c:6545:2: warning: #import is a deprecated GCC extension [-Wdeprecated]
 #import <ApplicationServices/ApplicationServices.h>
  ^
In file included from /usr/include/Availability.h:162:0,
                 from /usr/include/wchar.h:72,
                 from /Users/eric/Library/Caches/lambdanative/macosx/include/gambit.h:752,
                 from /Users/eric/Library/Caches/lambdanative/macosx/build/597850315.c:903:
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Headers/LSInfoDeprecated.h:1242:34: error: expected ',' or '}' before '__attribute__'
   kLSHandlerOptionsDefault       __OSX_AVAILABLE_BUT_DEPRECATED_MSG(__MAC_10_4, __MAC_10_11, __IPHONE_4_0, __IPHONE_9_0, "Creator codes are deprecated on OS X.") = 0,
                                  ^
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Headers/LSOpenDeprecated.h:27:33: error: expected ',' or '}' before '__attribute__'
   kLSLaunchStartClassic         __OSX_AVAILABLE_BUT_DEPRECATED_MSG(__MAC_10_0, __MAC_10_11, __IPHONE_NA, __IPHONE_NA, "The Classic environment is no longer supported.") = 0x00020000, /* Does nothing.*/
                                 ^
In file included from /System/Library/Frameworks/CoreGraphics.framework/Headers/CGContext.h:18:0,
                 from /System/Library/Frameworks/CoreGraphics.framework/Headers/CGBitmapContext.h:9,
                 from /System/Library/Frameworks/CoreGraphics.framework/Headers/CoreGraphics.h:11,
                 from /System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:35,
                 from /Users/eric/Library/Caches/lambdanative/macosx/build/597850315.c:6545:
/System/Library/Frameworks/CoreGraphics.framework/Headers/CGFont.h:53:40: error: initializer element is not constant
 static const CGFontIndex kCGGlyphMax = kCGFontIndexMax;
                                        ^
ERROR: failed on file /Users/eric/Library/Caches/lambdanative/macosx/build/597850315.o
BUILD FAILED - configure with verbose option for more information
make: *** [all] Error 1

== Instructions from CPetersen (at) cw.bc.ca on Gambit mailing list ==
git clone https://github.com/part-cw/lambdanative.git
cd lambdanative/
cp SETUP.template SETUP
cp PROFILE.template PROFILE
./configure DemoConsole
make
make install

I tried to investigate the problem and I suspect the problem is in running MacOSX 10.11 (El Capitan).
Any help welcome
Eric

**Comment by clpetersen** [comment] 2015-09-13 00:35
We don't have OS X 10.11 installed anywhere yet.. judging by the log messages the problem could be a deprecated import statement in ln_core, now removed in commit 84981a6. Please try if this fixes your build.

**Comment by mgorges** [comment] 2016-02-09 05:11
@clpetersen I don't think this was actually fixed. You got rid of the warning, but not the subsequent error. Reopening.

**Comment by clpetersen** [comment] 2016-03-07 22:16
I'm now on El Capitan, and the latest stable XCode. Everything appears to work fine, can build for iOS without issues. I cannot reproduce the problem, suspect it is related to the toolchain, possibly a non-standard compiler (gcc). If it persists, please provide more information and xcode + default compiler versions. Closing for now.

**Closed by clpetersen** 2016-03-07 22:16 UTC
Labels: bug

**Comment by magneticnorth** [comment] 2016-03-13 23:26
We get the same error("/System/Library/Frameworks/CoreGraphics.framework/Headers/CGFont.h:53:40: error: initializer element is not constant") when building graphviz with gcc-6

gcc-6 is from homebrew, and is up to date. gcc-6 --version says:
gcc-6 (Homebrew gcc6 6-20160221) 6.0.0 20160221 (experimental)

graphviz is from https://github.com/ellson/graphviz

I don't understand what might be wrong.

**Comment by clpetersen** [comment] 2016-03-14 15:10
All of this is possibly due to one or more bugs in XCode header files . Some have apparently been fixed in Command_Line_Tools_OS_X_10.11_for_Xcode_7.3_beta_5.dmg, which can be downloaded from the apple developer site. Might be worth a try.
