### ISSUE TITLE
Redcap get  instance

### ISSUE THREAD

**Issue by karliwalti** [part-cw/lambdanative#192] opened 2018-05-14 20:08 UTC
Suggestion for bug fix in returning correct next instance. returning 0 did not throw an error, but redcap cannot handle instance 0.

https://github.com/part-cw/lambdanative/blob/6c56a3b984ae82ddbd87be05bd0c02f5aa31be10/modules/redcap/redcap.scm#L458
```

       (begin (log-warning "Cannot retrieve instance number from REDCap. I assume this is the first entry.") 1)))

```

**Comment by mgorges** [comment] 2018-05-14 20:28
Sorry, also not sure what this one is about - duplicate of your pull request #164, which I fixed in the subsequent commits?

**Comment by karliwalti** [comment] 2018-05-14 20:40
apologies, did update comment to be more of a bugfix.

**Comment by nonphatic** [comment] 2018-05-25 21:59
Should we really be doing this? The edited line executes when `response` is false, which means something has gone wrong when executing `redcap-export-records`. Rather than returning `1` and pretending that everything is ok, we should propagate that error and also return `#f`. 

We should return `1` if `response` is an empty list, though, since in that case it just means that there's no pre-existing instance (and we already are doing that).

**Comment by karliwalti** [comment] 2018-05-26 04:55
`redcap-export-records` returns #f for many reasons, also for no records (and not an empty list). We did not dare to change the error management of 
` redcap-export-records`, but agree that this would be the nicer solution.

**Comment by karliwalti** [comment] 2018-05-26 06:39
@nonphatic  Thank you for questioning this.  I just did some additional tests and pinpointed the real issue. It was in  ` redcap:jsonstr->list`.  The response from redcap is followed by more caracters than just the empty message [] and will return false instead of an empty list. 
Following change will overcome the issue and be much cleaner:

testing for string content "[]"
```
(define (redcap:jsonstr->list str)
  (if (or (list? str) (fx< (string-length str) 3) (not (string-contains str "[{")) (not (string-contains str "}]")))
    ;; Determine whether content just empty or whether it was improperly formatted (possibly incomplete)
    (if (and (string? str) (fx>= (string-length str) 3) (not (string-contains str "[]"))) #f (list))
    (let* ((index (string-contains str "[{"))
           ;; Remove anything outside brackets first
           (output (json-decode (substring str index (string-length str)))))
      (if (json-error? output) #f (vector->list output))))
)
```

propagating error and returning 1 if empty list
```
;returns the index for instance in
(define (redcap-get-next-instance host token record form)
  (let* ((forms (if (pair? form) form (list form)))
       (records (if (pair? record) record (list record)))
       (maxinstance 0)
       (response (redcap-export-records host token 'forms forms 'records records 'type "eav"))  ;;currently redcap8.0 flat does not return instances
       (len (if response (length response) 0))
       )
    (if response
       (if (fx> len 0)
           (begin (let loop ((entries response))
            (if (fx> (length entries) 0)
              	(let* ((row (car entries))
                       (val (alist-ref row "redcap_repeat_instance" 0))
                       (instrument (alist-ref row "redcap_repeat_instrument" #f))
                       (instance  (if (string? val) (string->number (string-remove-quotes val)) val)))
                      (if (not instrument) (log-warning "Exported REDcap instrument " (car forms) " is not repeatable"))
                      (if (fx> instance maxinstance) (set! maxinstance instance))
                      (loop (cdr entries))))) (fx+ maxinstance 1))
           (begin (log-warning "Exported REDcap record has no repeated entry yet") 1))
       (begin (log-error "Cannot retrieve instance number from REDCap.") #f)))
)
```

**Comment by nonphatic** [comment] 2018-05-28 16:59
@karliwalti If the response is the string `[]` followed by one or more characters that don't constitute valid JSON, doesn't that mean `(or (list? str) (fx< (string-length str) 3) (not (string-contains str "[{")) (not (string-contains str "}]")))` is `false`? Then the inner `if` won't be reached. 

What extra characters are you seeing after `[]`? If it's just some newlines then we can strip the string first, and the remaining code will correctly handle it.

**Comment by nonphatic** [comment] 2018-05-28 18:00
I see. If you're sure that `[]` followed by that error message should be interpreted as an empty record, then I propose the following:

```
(define (redcap:jsonstr->list str)
  (cond ((and (string? str) (string-contains str "[{") (string-contains str "}]"))
          (let* ((index (string-contains str "[{"))
                 ;; Remove anything outside brackets first
                 (output (json-decode (substring str index (string-length str)))))
            (if (json-error? output) #f (vector->list output))))
        ((or (list? str) (and (string? str) (string-contains str "[]"))) '())
        (else #f)))
```

Just so that it's clear that a list input should return `'()`, a string of the form `"[{...}]"` is assumed to be valid JSON, any other string with `[]` is assumed to be an empty record and should also return `'()`, and anything else (`#f`, other strings, etc.) is invalid and should return `#f`.

**Comment by karliwalti** [comment] 2018-05-28 18:06
Agree, this would produce same result, but would be clearer.

Good suggestion. Thx

**Closed** 2018-05-28 18:12 UTC
