### ISSUE TITLE
Build failure of demo apps on MacOS High Sierra: missing SDK; git repo hangup

### ISSUE THREAD

**Issue by uma-hh** [part-cw/lambdanative#177] opened 2018-03-06 16:07 UTC
Hi,
I was unable to build the following example apps:

* DemoHelloWorld
* DemoRTAudio
* DemoVoiP
* uSquish

Each time the error was:

```
configure: error: Couldn't find 10.5, 10.6, 10.7, 10.8, 10.9, 10.10, 10.11, or 10.12 SDK
ERROR: failed with exit code 64
>> configure failed
BUILD FAILED - configure with verbose option for more information
make: *** [all] Error 1
````

I am with Xcode 9.2 on MacOS 10.13 (High Sierra).

In addition, building

* DemoBarcode

failed with

````
 => cloning git://git.code.sf.net/p/zint/code..
git clone  git://git.code.sf.net/p/zint/code
Cloning into 'code'...
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
ERROR: failed with exit code 128
>> repository cloning failed [git://git.code.sf.net/p/zint/code]
BUILD FAILED - configure with verbose option for more information
make: *** [all] Error 1
````

The other apps did build without error when I had installed the proper libraries.

All build attepts in lambdanative dir simply with

````
./configure NameOfApp
make
`````

Best,
Ulf

**Comment by mgorges** [comment] 2018-03-06 19:01
The first point is something I tried to fix in commit 8c27bd2. However, I can't test it as I don't want to break my current setup with XCode 8.3 which works for iOS.

The second point regarding [Zint](https://sourceforge.net/p/zint/code/ci/master/tree/) I can't reproduce - the website is very slow, maybe experiencing leftover issues from their major outage from March 1st? However, in the end it did complete the clone for me - maybe we need to package a binary archive instead?

**Comment by mgorges** [comment] 2018-03-06 19:09
Commit 3407013 switches the repository source for zint to Github, which might be faster.

**Comment by uma-hh** [comment] 2018-03-06 21:53
As to point two, I now get this:

```
 => cloning git@github.com:woo-j/zint.git..
The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
git clone  git@github.com:woo-j/zint.git
Cloning into 'zint'...
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
ERROR: failed with exit code 128
>> repository cloning failed [git@github.com:woo-j/zint.git]
BUILD FAILED - configure with verbose option for more information
make: *** [all] Error 1
```

The download failure may indeed be related to the early March outage of Sourceforge. At least on 2018-03-04 I was unable to build even the Calculator because some required lib (libpng, if I remember correctly) could not be downloaded. That issue went away two days later.

As to point one: a am relatively new to Mac (from Linux), so I don't know much about these XCode issues; only that Apple is not known for their mercy with soft- & hardware they consider outdated. Therefore, I am not sure if it is a wise strategy to advertise LamdaNative as ready for crossplatform while not making it possible to compile with up to date development tools. If LambdaNative cannot be used with XCode 9.2 (I am not going to install earlier versions), I won't use use it.

**Comment by mgorges** [comment] 2018-03-06 22:16
Cloning issue without SSH private key fixed in commit d6a7b25.

**Comment by uma-hh** [comment] 2018-03-06 22:23
And works!

As to the XCode version stuff. It seems that it is possible to have multiple versions installed. E.g.

* https://medium.com/@hacknicity/working-with-multiple-versions-of-xcode-e331c01aa6bc
* http://iosbrain.com/blog/2017/01/02/installing-multiple-versions-of-xcode-6-7-8-side-by-side-together-on-the-same-mac/

And more per Google. So it seems to be possible to have a working development stack side by side with Apples newest incarnations. But, as I said, no experience on my side at the moment.
Cheers.

**Comment by mgorges** [comment] 2018-03-06 22:24
As for your final point you are welcome to help fix issue [160](https://github.com/part-cw/lambdanative/issues/160), which is not trivial as Apple removed the code signing tool needed when not building from within XCode and now requires a bunch of XML-based build tools to be used instead. At the current point we don't support any version of Xcode newer than 8.3, which I appreciate is from September 2017. If it were an easy fix, I had already done, but I currently don't have the time for it - sorry!
--> If you need newer Xcode support immediately, you'll have to look for a solution other than LambdaNative!

**Closed** 2018-03-12 05:26 UTC
Labels: bug
