### ISSUE TITLE
(time-difference t1 t2) does not accept time objects

### ISSUE THREAD

**Issue by mhueser** [part-cw/lambdanative#87] opened 2015-12-13 21:26 UTC
PLATFORM: Linux
REVISION: Most recent commit as of today

The following statement segmentation faults:

  (set! foo (time-difference (current-time) (current-time)))

[It is called in the event loop of the program.]

Putting debugging statements into the implementation

(define (tm:time-difference time1 time2 time3)
  (display "tm:time-difference BEGIN \n")
  (display (time? time1)) (display "\n")
  (display (time? time2)) (display "\n")
  (display (time-type time1)) (display "\n")
  (display (time-type time2)) (display "\n")
...
)

brings the following result:

tm:time-difference BEGIN 
#f
#f
1450048854.2384715
1450048854.2384717

which surprised me. (time? (current-time)) should yield TRUE.

**Comment by mgorges** [comment] 2015-12-15 13:03
According to the Gambit manual's [Measuring Time](http://www.iro.umontreal.ca/~gambit/doc/gambit.html#Measuring-time) section you are correct that `(time? (current-time))` should yield `#t` - however, it doesn't! This seems to be a LambdaNative bug, present with both Gambit 4.7.9 and 4.7.3 as DemoConsole fails in both instances, while both `gsi`s work as expected. - Not sure where to start investigating but will get digging.

**Comment by mhueser** [comment] 2015-12-15 16:33
It almost looks to me that the time representation's fields are mixed up. Also (time-type t) gives unexpected results; namely the presumably seconds since the epoch or something related.

**Comment by clpetersen** [comment] 2015-12-15 16:39
I believe this issue is caused by a naming conflict between the gambit time functions and SRFI 19, which is included in ln_core (time.scm). It's easy to fix by adding a namespace, but we will need to make sure that all the right functions remain exposed. Thanks for spotting this, I'll have a look at a patch.

**Comment by clpetersen** [comment] 2015-12-15 19:29
This is now fixed in commit `c9cf9`. The problem was that the SRFI 19 code defines a record called `time` which conflicts with the gambit internals. `(time? (current-time))` now return `#t` as it should. Please note that (current-time) is not compatible with the SRFI 19 functions.

**Closed by clpetersen** 2015-12-15 19:29 UTC
Labels: bug
