### ISSUE TITLE
Segfault in Calculator

### ISSUE THREAD

**Issue by rgh36167** [part-cw/lambdanative#179] opened 2018-03-09 21:42 UTC
Start it and hit "=" - results in an segfault on Linux and Android. Even with debugging enabled no clue what happened:

```
Program received signal SIGSEGV, Segmentation fault.
0x41b940d0 in siglongjmp () from /lib/libc.so.6
```

**Comment by mgorges** [comment] 2018-03-10 00:15
The problem is that [apps/Calculator/main.scm#L76](https://github.com/part-cw/lambdanative/blob/master/apps/Calculator/main.scm#L76) returns `#!void` as the string is `\\;`. This causes a segfault as the call of `flo` in [apps/Calculator/main.scm#L62](https://github.com/part-cw/lambdanative/blob/master/apps/Calculator/main.scm#L62) has `(declare (not safe))`. - Fixed in 75ef07c

**Closed by mgorges** 2018-03-10 00:15 UTC

**Comment by rgh36167** [comment] 2018-03-10 11:34
I can see where the error is but how do you find out that? Despite compiling with debug gdb gives no useful clue here.

**Comment by mgorges** [comment] 2018-03-10 21:51
The problem is that these `not safe` things are very hard to debug - as are error in the low level functions like `fl+`. I knew the error had to be in the `(calculator-evaluate)` function, so I started by logging / displaying the variables that came out of the let. - For your error condition `res` was `#!void`, which I knew `flo` would choke on.

**Comment by mgorges** [comment] 2018-03-10 21:52
Sometimes rebuilding everything in `debug` mode helps, but as I said low-level function segfaults are hard to track down.

**Comment by rgh36167** [comment] 2018-03-10 22:04
I see, hoped that for debugging it would be possible to replace the unsafe functions with safe ones by some magic switch.

**Comment by mgorges** [comment] 2018-03-11 00:06
You encountered a segfault with a low-level function, which is pretty rare - typically if you configure with `debug` you get good location information for your error. You could modify [languages/scm.sh#L55](https://github.com/part-cw/lambdanative/blob/master/languages/scm.sh#L55) to omit the `(not safe)` but be aware that this has a pretty decent impact on performance, as well as that there might be additional places where `(not safe)` is used in the codebase.

**Comment by rgh36167** [comment] 2018-03-15 20:02
I was surprised that gsc doesn't catch very simple errors like calling a previously localy defined scheme function with fewer arguments than required ..  the code segfaults instead.

```
(define (fac x)
  (if (< x 3) x
        (* x (fac (- x 1))))
  )

(fac)
```
Is there some flag to catch such errors?

**Comment by mgorges** [comment] 2018-03-15 22:02
There might be, but this is probably a question better posed in the [Gambit issue tracker](https://github.com/gambit/gambit/issues)? Also [Issues 115](https://github.com/part-cw/lambdanative/issues/115) has some pointers as well as the Wiki article on [Debugging](https://github.com/part-cw/lambdanative/wiki/Debugging).

**Comment by rgh36167** [comment] 2018-03-19 22:48
I have created https://github.com/gambit/gambit/issues/342 

After some more tests noticed that the lambdanative compilation method seems to break something: if I compile the broken fac.scm with ```gsc -exe fac.scm``` the executable will complain about wrong number of arguments at least at runtime. In lambdanative however I do not get any message and depending on context either a segfault or other unexpected behaviour.
