### ISSUE TITLE
Failed to build DemoHelloWorld ios on XCode 9.2

### ISSUE THREAD

**Issue by tgruben** [part-cw/lambdanative#175] opened 2018-01-24 15:38 UTC
Just working through the getting started get and the DemoHelloWorld ios step failed with
```
clang: warning: argument unused during compilation: '-L/Users/toddgruben/Library/Caches/lambdanative/ios/arm64/lib' [-Wunused-command-line-argument]
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk -DIOS -DIPHONE -miphoneos-version-min=5.1.1 -fPIC -fsigned-char -fomit-frame-pointer -I/Users/toddgruben/Library/Caches/lambdanative/ios/arm64/include -L/Users/toddgruben/Library/Caches/lambdanative/ios/arm64/lib -Wno-unused -Wno-write-strings -O1 -fno-math-errno -fno-strict-aliasing -fwrapv -fomit-frame-pointer -fPIC -fno-common   -I"../include" -c -o "os_shell.o" -I. -DHAVE_CONFIG_H -D___GAMBCDIR="\"/Users/toddgruben/Library/Caches/lambdanative/ios/arm64\"" -D___SYS_TYPE_CPU="\"arm\"" -D___SYS_TYPE_VENDOR="\"unknown\"" -D___SYS_TYPE_OS="\"none\"" -D___CONFIGURE_COMMAND="\"./configure '--prefix=/Users/toddgruben/Library/Caches/lambdanative/ios/arm64' '--host=arm' 'host_alias=arm' 'CC=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk -DIOS -DIPHONE -miphoneos-version-min=5.1.1 -fPIC -fsigned-char -fomit-frame-pointer -I/Users/toddgruben/Library/Caches/lambdanative/ios/arm64/include -L/Users/toddgruben/Library/Caches/lambdanative/ios/arm64/lib' 'LDFLAGS=-L/Users/toddgruben/Library/Caches/lambdanative/ios/arm64/lib' 'CPPFLAGS=-I/Users/toddgruben/Library/Caches/lambdanative/ios/arm64/include' 'CPP='"\" -D___OBJ_EXTENSION="\".o\"" -D___EXE_EXTENSION="\"\"" -D___BAT_EXTENSION="\"\"" -D___PRIMAL os_shell.c -D___LIBRARY
clang: warning: argument unused during compilation: '-L/Users/toddgruben/Library/Caches/lambdanative/ios/arm64/lib' [-Wunused-command-line-argument]
os_shell.c:831:14: error: 'system' is unavailable: not available on iOS
      code = system (ccmd);
             ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/usr/include/stdlib.h:195:6: note: 'system' has been explicitly marked unavailable here
int      system(const char *) __DARWIN_ALIAS_C(system);
         ^
1 error generated.
make[1]: *** [os_shell.o] Error 1
ERROR: failed with exit code 2
>> make failed
```
running a clean install of ios seirra  with the lastest XCode 9.2.

Any Suggestions?

**Comment by mgorges** [comment] 2018-01-24 17:48
Duplicate of Issue [172](https://github.com/part-cw/lambdanative/issues/172) - please look there for a potential patch, which we have yet to integrate into the main branch

**Closed by mgorges** 2018-01-24 17:48 UTC

**Comment by tgruben** [comment] 2018-01-24 18:00
sorry I missed that, thanks.
